import { BaseDefense, DefenseData } from "../../../../models/Defenses";

export const data: DefenseData = {
  id: "123214124",
  name: "Defesa Aérea",
  hitpoints: [
    "800",
    "850",
    "900",
    "950",
    "1000",
    "1050",
    "1100",
    "1200",
    "1300",
    "1400",
    "1500",
    "1600",
  ],
  imageUrl: [
    "../../../../assets/images/defenses/airdefenses/14_1.png",
    "../../../../assets/images/defenses/airdefenses/14_2.png",
    "../../../../assets/images/defenses/airdefenses/14_3.png",
    "../../../../assets/images/defenses/airdefenses/14_4.png",
    "../../../../assets/images/defenses/airdefenses/14_5.png",
    "../../../../assets/images/defenses/airdefenses/14_6.png",
    "../../../../assets/images/defenses/airdefenses/14_7.png",
    "../../../../assets/images/defenses/airdefenses/14_8.png",
    "../../../../assets/images/defenses/airdefenses/14_9.png",
    "../../../../assets/images/defenses/airdefenses/14_10.png",
    "../../../../assets/images/defenses/airdefenses/14_11.png",
    "../../../../assets/images/defenses/airdefenses/14_12.png",
  ],
  maxLevel: 12,
};
